### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by volodchenkov** [jazzband/silk#229]
I have this error after update: 
```shell
 File "/Users/izvr/Projects/bet/env/lib/python3.6/site-packages/silk/models.py", line 135, in Response
    request = OneToOneField(Request, related_name='response', db_index=True)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by jkeyes** [comment]
Two issues I've found:

* adding `on_delete` to `ForeignKey` and `OneToOneField` declarations (models.py)
* `MIDDLEWARE_CLASSES` is no longer available from `settings` (profiler.py)

**Comment by jkeyes** [comment]
Gah!  I see these are covered in PR #227

**Comment by volodchenkov** [comment]
I receive this error with version django-silk==1.0.0 installed from pip

**Comment by albertyw** [comment]
#227 has been landed and I'm running a small django 2 site with that PR now.  

If you want to get django 2 support now, you can pip install directly from github (maybe pin to the current master commit).  Otherwise, I'm going to work on #187 and make a new release (maybe v1.1.0 but I need to check the commit history for semantic versioning).

**Comment by physicalattraction** [comment]
I also see this error when executing `runserver` from the `projects` directory:

```
    include('silk.urls', namespace='silk', app_name='silk')
TypeError: include() got an unexpected keyword argument 'app_name'
```

**Comment by yousifa** [comment]
any update on when this will be pulled/next release tagged?

**Comment by albertyw** [comment]
@yousifa I'm working through getting django 2 tests working in #233.  It's quite slow going because I can't replicate the test environment locally.  I'm hoping to fix the issues and make a new release within a week.

@physicalattraction there's a patch for your error in #233.  Technically, that doesn't block the next release of silk because the projects directory is only used in tests.

**Comment by sebatyler** [comment]
1.1.0 released but not yet deployed to pip.
https://pypi.python.org/pypi/django-silk

When can I use 1.1.0 with pip?

**Comment by avelis** [comment]
@sebatyler I don't have an ETA at the moment on the publish to PyPi. For now I suggest a way to reference the release directly in any requirements files you may use.

**Comment by sebatyler** [comment]
@avelis  Do you have any reason not to have ETA?
I just wonder.

**Comment by avelis** [comment]
@sebatyler I am unsure if Jazzband has the right privileges to publish releases to Django-Silk's Pypi account. I don't have access to verify this. I could also be missing a couple other steps to ensure proper state as a Jazzband project.

**Comment by sebatyler** [comment]
@avelis ah... It's unfortunate. I hope it will be resolved. Thank you!

**Comment by albertyw** [comment]
Since this is more a discussion of releases rather than django 2 support (master should fully support django 2 now), I moved the discussion to #187 and https://github.com/jazzband/roadies/issues/82
